name: Continuous Integration (CI)

on:
  pull_request:
  push:
    branches:
<<<<<<< HEAD
      - iron
  pull_request:
=======
      - ros2
>>>>>>> b4ac968 (Finished connection timeout implementation and renamed packages)
  workflow_dispatch:

jobs:
  pre-commit:
    name: CI
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        env:
<<<<<<< HEAD
          - IMAGE: iron-ci
            ROS_DISTRO: iron
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log into registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
=======
          - ROS_DISTRO: rolling
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
>>>>>>> b4ac968 (Finished connection timeout implementation and renamed packages)

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
<<<<<<< HEAD
<<<<<<< HEAD
          DOCKER_IMAGE: ghcr.io/robotic-decision-making-lab/ros2-template:${{ matrix.env.IMAGE }}
=======
          DOCKER_IMAGE: ghcr.io/robotic-decision-making-lab/libwaterlinked:${{ matrix.env.IMAGE }}
>>>>>>> cc84fbc (Finished initial implementation of driver and renamed to libwaterlinked)
          CXXFLAGS: >-
            -Wall -Wextra -Wpedantic -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls
          CC: ${{ env.CLANG_TIDY && 'clang' }}
          CXX: ${{ env.CLANG_TIDY && 'clang++' }}
=======
          ROS_DISTRO: ${{ matrix.env.ROS_DISTRO }}
          CXXFLAGS: -Wall -Wextra -Wpedantic
          CLANG_TIDY: true
          UPSTREAM_WORKSPACE: ros2.repos
          AFTER_SETUP_UPSTREAM_WORKSPACE: vcs pull $BASEDIR/upstream_ws/src
          AFTER_SETUP_DOWNSTREAM_WORKSPACE: vcs pull $BASEDIR/downstream_ws/src
>>>>>>> b4ac968 (Finished connection timeout implementation and renamed packages)
