name: Continuous Integration (CI)

on:
  pull_request:
  push:
    branches:
      - ros2
  workflow_dispatch:

jobs:
  pre-commit:
    name: CI
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: rolling
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ROS Industrial CI
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.env.ROS_DISTRO }}
          CXXFLAGS: -Wall -Wextra -Wpedantic
          CLANG_TIDY: true
          UPSTREAM_WORKSPACE: ros2.repos
          AFTER_SETUP_UPSTREAM_WORKSPACE: vcs pull $BASEDIR/upstream_ws/src
          AFTER_SETUP_DOWNSTREAM_WORKSPACE: vcs pull $BASEDIR/downstream_ws/src
          ROSDEP_SKIP_KEYS: nlohmann_json
